# Generated by Django 5.0 on 2024-01-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='created_at',
        ),
    ]
